export '../../../flutter_flow/lat_lng.dart';
export 'package:supabase_flutter/supabase_flutter.dart' hide Provider;

export '../supabase.dart';
export 'row.dart';
export 'table.dart';

export 'tables/despesas.dart';
export 'tables/aulas.dart';
export 'tables/lancamentos_metas.dart';
export 'tables/respostas.dart';
export 'tables/metas.dart';
export 'tables/treinamentos.dart';
export 'tables/chats.dart';
export 'tables/progresso_formacao.dart';
export 'tables/perguntas.dart';
export 'tables/empresas.dart';
export 'tables/companies.dart';
export 'tables/tipos_despesa.dart';
export 'tables/certificados_emitidos.dart';
export 'tables/progresso_treinamento.dart';
export 'tables/funcionalidades.dart';
export 'tables/messages.dart';
export 'tables/checklist_respostas.dart';
export 'tables/formacoes.dart';
export 'tables/users.dart';
export 'tables/metas_usuarios.dart';
export 'tables/chat_files.dart';
export 'tables/checklist_itens.dart';
export 'tables/plano_funcionalidades.dart';
export 'tables/checklists.dart';
export 'tables/filiais.dart';
export 'tables/checklist_modelos.dart';
